### PR TITLE
feat(actions): add pytest actions and update word_tokenizer

### PR DESCRIPTION
**Pull request by sergialonsaco**
- github actions with pytest and flake8 have been added.

- in order to fix issue with text contractions, word_tokenize has been substituted with Tweetokenize

### CODE REVIEW

**Comment by sergialonsaco** [comment]
it should be nice to add a GitHub action to publish newest versions to the official PyPI org

**Comment by daltonfury42** [comment]
I'll merge your changes for now, and work on this over the weekend. Thanks

**Comment by daltonfury42** [comment]
@sergialonsaco I was playing around with GitHub Actions today. Thanks for letting me know about this awesome feature!

**Comment by sergialonsaco** [comment]
> @sergialonsaco I was playing around with GitHub Actions today. Thanks for letting me know about this awesome feature!

I'm glad to hear that! I discovered it a few weeks ago, it is a cool CI tool integrated with github, let's take profit of it. Maybe good learning would be to create your own actions (idk if it would be really useful to have a truecase-github-action, but it could be a good project to learn).

**Pull request merged**
